### ISSUE TITLE
Executor hangs when guest attempts to read more input than is provided

### ISSUE THREAD

**Issue by nategraf** [risc0/risc0#1016]
When a guest in run in the Executor, and not enough input is provided, the process hangs. In particular this is caused when the guest calls `env::read()` and no more input is provided in the `ExecutorEnv` to pass to the guest.

I've not yet investigated the root cause, or have a suggestion of how to fix this. It also relates to a more general question of input handling, especially in the client-server model where it is perfectly valid for the client to provide to the server input to the guest in a streaming manner.

**Comment by austinabell** [comment]
Looked briefly into this to understand how the system currently communicates.

The read that is blocking is:

https://github.com/risc0/risc0/blob/e48f779d2ce66b0af274ca4881c8da5df405cebe/risc0/zkvm/src/host/api/client.rs#L473

And this is because when there is no input, the default STDIN reader is defaulted to stdin https://github.com/risc0/risc0/blob/e48f779d2ce66b0af274ca4881c8da5df405cebe/risc0/zkvm/src/host/client/posix_io.rs#L37

Which there isn't an unopinionated way to get around the blocking aspect of this API. I'm also very unclear around why this is the default or how it is or would be used like this.

I'll open a PR with what intuitively makes sense for a fix of this, but I might be missing some other workflows. I'll explain what I used to test the fix.
