### ISSUE TITLE
trivial factors in hello world

### ISSUE THREAD

**Issue by hroger1030** [risc0/risc0#1081]
Hi,  
  
Ok, this is probably a truly trivial nitpick, and I would rate it about p6 bug under most circumstances. I just was browsing about your site to do some research about the company for a job application, and I noticed this line in your hello world tutorial .md:
    
    // Verify that neither of them are 1 (i.e. nontrivial factors)
    if a == 1 || b == 1 {
        panic!("Trivial factors")
    }
    
This might be a deliberately simplified check to keep things simple for the demo, but wouldn't you want to also panic if either of the factors are -1 or 0?  This seems like a pretty minor given the context, but I just wanted to point it out in case you want to fix it.  If you are going to check for trivial factors, you might want to get all of them [1,0,-1].

**Comment by tzerrell** [comment]
Since the inputs are unsigned integers (i.e. nonnegative), `-1` is already not possible. If it _were_ possible that would be a fairly substantial bug for this use case (Proving "I know the factors of 17" with those factors being `-1` and `-17` would not be working as intended).

As for 0 -- I personally find "I know the factors of 0" not a problem in this context -- so does anyone with a basic math background, its factors are "0" and "literally anything". That said, requiring `a > 1`, `b > 1` would also be reasonable.
