### ISSUE TITLE
Unable to build r0vm in a sandboxed environment

### ISSUE THREAD

**Issue by marijanp** [risc0/risc0#1180]
Hi, I'm packaging the r0vm using [Nix](https://nixos.org). Because the recursion `build.rs` downloads ([see](https://github.com/risc0/risc0/blob/main/risc0/circuit/recursion/build.rs)) some files at build time it violates Nix's sandboxing, which does not allow any connection to the internet during build-time.

The question that arises is what `recursion_zkr.zip` is and why It's not shipped with the sources. And secondly whether it would be possible to make the `SRC_PATH` not a constant, but read it from an environment variable and default to `src/recursion_zkr.zip`.

I'm happy to submit a PR if that is acceptable.

**Comment by flaub** [comment]
This file is over 50MB currently and contains firmware code that is executed by the recursion circuit. I haven't yet found a way to make this code available as normal source since GitHub has a limit on the size that files can be that's checked in. So right now it's using LFS and then the build script downloads it at build time. I realize this is less than ideal and I'm looking for alternatives.

**Comment by flaub** [comment]
The docs.rs build failure is already known, see: https://github.com/risc0/risc0/issues/1048

**Comment by marijanp** [comment]
I see, but could you answer the prior question:
Would you accept a PR making SRC_PATH not a constant, but read it from an environment variable and default to src/recursion_zkr.zip.

**Comment by marijanp** [comment]
@flaub I've created a PR #1192

**Comment by flaub** [comment]
Hopefully this works for you!
