### ISSUE TITLE
[Feature] Support for proving the invalidity of a RISC Zero receipt

### ISSUE THREAD

**Issue by nategraf** [risc0/risc0#1355]
## Feature

Users have requested a mechanism by which they can prove the invalidity of a given RISC Zero receipt. Note that this is not verifying the _validity_ of a RISC Zero receipt, nor is it proving that a valid receipt for a given `ReceiptClaim` does not exist.

## Motivation

In certain settings a party will commit to a `Receipt`, or otherwise have a given receipt for which it must be shown definitively whether that given receipt is valid, or invalid. In these cases, composition cannot satisfy the requirements. In particular, composition can prove the existence of some valid receipt for a given `ReceiptClaim`, but it cannot prove non-existence and it cannot act on a fixed `Receipt` is valid or invalid.

## Implementation

By far the simplest implementation of this would be run the `Receipt` verifier in the zkVM. We previously had support for this, but have not maintained it. This issue would be resolved by a PR to get this functionality working again.

**Comment by weikengchen** [comment]
It seems RISC-V VM is not going to be good, but the recursion-specific one can. 

Currently, this is a bit challenging because the recursive proof system only has "assert_eq!"-like instruction?
https://github.com/l2iterative/ll0/blob/master/src/structures/mod.rs#L46C5-L47C28

And the solution is to change how this instruction works? Instead of requiring something to be the same, it increments a counter if it is not the same, and the counter is used at the end? 

This seems to require one more data column for that counter, a data column for "is_zero", and a data column for "inv"
- is_zero * (is_zero - 1) == 0
- is_zero * (a - b) == 0
- (is_zero - 1) * inv * (a - b) == 1
- counter = counter_prev + is_zero

**Comment by nategraf** [comment]
So one of the key requirements here is that it verifies that a specific committed receipt is checked, rather than one that is provided a witness input. I imagine this is surmountable, but a large new requirement over the existing recursion circuit. I think given the lift required to get a custom-circuit based approach working, and the niche application of this use case so far, the poor rv32im performance is going to be acceptable.

**Comment by nategraf** [comment]
Adding to the requirements of a solutions here: the most clear use case of showing a committed RISC Zero receipt as invalid, fraud proofs within an optimistic system, requires that the verifier be panic-free with respect to the receipt, such that it is not possible for someone to generate an invalid receipt that cannot be proven to be invalid.

**Comment by flaub** [comment]
I believe we got verify to run inside the guest, so closing this.
