### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by UltraDoge** [risc0/risc0#1701]
file:///home/linux/p0tion-tmp/node_modules/@p0tion/phase2cli/dist/index.js:860
        const contributionHash = matchContributionHash?.at(0)?.replace("\n\t\t", "");
                                                       ^

SyntaxError: Unexpected token '.'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)
linux@linux-virtual-machine:~/p0tion-tmp$ npx phase2cli contribute
file:///home/linux/p0tion-tmp/node_modules/@p0tion/phase2cli/dist/index.js:860
        const contributionHash = matchContributionHash?.at(0)?.replace("\n\t\t", "");
                                                       ^

SyntaxError: Unexpected token '.'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)

**Comment by tzerrell** [comment]
Possibly a version issue, are you sure you are using the latest phase2cli version and the nvm version specified in https://r0.link/TSC? ... or otherwise, the code cited in this message is from the [p0tion repo](https://github.com/privacy-scaling-explorations/p0tion) tests (e.g. https://github.com/privacy-scaling-explorations/p0tion/blob/f88bcee5d499dce975d0592ed10b21aa8d73bbd2/packages/actions/test/unit/ec2.test.ts#L456), not this repo.
