### ISSUE TITLE
Ceremony

### ISSUE THREAD

**Issue by Unicorn1807** [risc0/risc0#1702]
The system was stopped for some reasons while participating in the Ceremony, then I entered the necessary commands to participate again, but my turn has not yet arrived, what is the reason for this?

**Comment by tzerrell** [comment]
Once your turn comes, there's a timeout period for making your contribution. If you have problems (e.g. internet goes out, computer goes to sleep), you need to resolve them and contribute before the timeout period ends; otherwise, you need to rejoin at the end of the queue. This ensures we can keep the ceremony open and allow others to participate even when someone is having technical issues.
