### ISSUE TITLE
[Documentation] Bonsai client version

### ISSUE THREAD

**Issue by kpp** [risc0/risc0#1920]
## User's Objective

Does Bonsai API support version 1 or only 0.21.0?

**Comment by flaub** [comment]
I believe the plan is to have Bonsai updated within the next week: @mothran?

**Comment by mothran** [comment]
Yup Bonsai lags behind the zkvm slight. We will have a update to bonsai within the next or so, date TDB

**Comment by zie1ony** [comment]
I'll wait. Thanks :)

**Comment by nuke-web3** [comment]
As this is related, I wanted to copy over a note for this thread:

Hello from the Bonsai Team!

We will be doing some major updating and in order to do so we will be taking Bonsai down for a short migration window.

**On Thursday June 13th (6/13/24) at 11am PST (or 6pm UTC) Bonsai Proving Service will go down for a 4 hour maintenance after which we will announce on discord in the #🎋｜bonsai  channel that the service is back up.**

:warning:  After which the following **all existing data will be flushed for all users**:
* Images 
* Inputs
* Receipts
* Guest logs

**Comment by nuke-web3** [comment]
So it's not documented explicitly yet in our dev.risczero.com site, but there is an API call you can check what the supported verion is:

https://api.bonsai.xyz/swagger-ui/#/version/route_version_data

Request an API key to access that endpoint: https://www.bonsai.xyz/

**Comment by pdg744** [comment]
Bonsai is using Version 1.0 now
