### ISSUE TITLE
[Bug] Assertion failure (IOT instruction) panic while executing a circuit

### ISSUE THREAD

**Issue by pventuzelo** [risc0/risc0#532]
# Assertion failure (IOT instruction) panic while executing a circuit

We (@fuzzinglabs & @lambdaclass) found an Assertion failure (IOT instruction) issue in risc0 while executing a circuit.

## Expected Behavior

It should not crash.

## Your Environment

-  e862e0a4d940dce9618f673b6503751b1bc20608
-  cargo 1.70.0-nightly (15d090969 2023-03-21)
-  Ubuntu 22.04

## Steps to reproduce

Download: 

Testing program:
``` rust
use risc0_circuit_rv32im::CircuitImpl;
use risc0_core::field::{baby_bear::BabyBearElem};
use risc0_zkp::{
    adapter::{CircuitStep, CircuitStepContext, CircuitStepHandler},
    hal::cpu::{CpuBuffer},
};

struct CustomStepMock {}

impl CircuitStepHandler<BabyBearElem> for CustomStepMock {
    fn call(
        &mut self,
        _cycle: usize,
        name: &str,
        extra: &str,
        args: &[BabyBearElem],
        outs: &mut [BabyBearElem],
    ) -> anyhow::Result<()> {
        println!("name: {name}, extra: {extra}, args: {args:?}");
        outs[0] = BabyBearElem::new(2);
        Ok(())
    }

    fn sort(&mut self, _name: &str) {
        unimplemented!()
    }
    fn calc_prefix_products(&mut self) {
        unimplemented!()
    }
}

pub fn main() {
    let circuit = CircuitImpl::new();
    let mut custom = CustomStepMock {};
    let ctx = CircuitStepContext { size: 0, cycle: 0 };
    let data_vec : Vec<u8>= vec![0x96, 0xff, 0xff, 0xff, 0xfe, 0xff, 0xff, 0xff];
    let args0 = CpuBuffer::from_fn(20, |_| BabyBearElem::new(data_vec[0].into()));
    let args1 = CpuBuffer::from_fn(20, |_| BabyBearElem::new(data_vec[1].into()));
    let args2 = CpuBuffer::from_fn(20, |_| BabyBearElem::new(data_vec[2].into()));
    let args = [&args0, &args1, &args2].map(CpuBuffer::as_slice_sync);
    circuit
        .step_exec(&ctx, &mut custom, args.as_slice())
        .unwrap();
}
```

## Root cause

```
step_exec: cxx/step_exec.cpp:240: risc0::Fp risc0::circuit::rv32im::step_exec(void*, void (*)(void*, const char*, const char*, const risc0::Fp*, size_t, risc0::Fp*, size_t), size_t, size_t, risc0::Fp**): Assertion `reg == Fp::invalid() || reg == x92' failed.
[1]    255466 IOT instruction
```

Related code: https://github.com/risc0/risc0/blob/08b89140bbf1b28f87b62cbc2cdac8e9820af72b/risc0/circuit/rv32im-sys/cxx/step_exec.cpp
Line : 240

**Comment by jbruestle** [comment]
What is the threat model here?  The autogenerated asserts in the step function are specifically placed to prevent invalid witnesses from moving any further into the prover pipeline (where they would later fail to meet the proper polynomial constraints anyway) to allow easier debugging of witness generation, but certainly if you directly send nonsense into the step function it will fail as expected.  This is why we  use assert rather than say 'throw' since we don't want to bother with these checks in release builds as they are only a debugging aid.  This is not a bug and is working as expected to reject invalid witness data.
