### ISSUE TITLE
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Session limit exceeded'

### ISSUE THREAD

**Issue by hu55a1n1** [risc0/risc0#633]
The code panics on this line where I run the executor ->
```rust
let session = exec.run().unwrap();
```

I was experimenting with basic arithmetic in the guest, and everything seems to work fine when the input isn't large. The code panics only when the input is large (i.e. ~500KB). 
```rust
let env = ExecutorEnv::builder()
    .add_input(&serde::to_vec(&data_500KB).unwrap())
    .build();
```

Is there a better way to share data between the host/guest?

**Comment by nategraf** [comment]
One note is that when you use `serde::to_vec` it will be serialized by the host and deserialized by the guest. If you just want to pass raw data, you can use `.add_input(&data)` to write without serialization and `risc0_zkvm::guest::env::read_slice` to read a slice of known length without deserialization.

The immediate error you are hitting is because you are exceeding the default session limit for how long a guest can run. Setting `.session_limit(...)` on the executor can raise the limit. (In a future version we will also be removing the default limit such that computations can, by default, run as long as they need)

https://docs.rs/risc0-zkvm/latest/risc0_zkvm/struct.ExecutorEnvBuilder.html#method.session_limit

**Comment by flaub** [comment]
We've recently made the session limit optional with https://github.com/risc0/risc0/pull/608.

I'll close this for now but if you're still running into trouble feel free to re-open.
