### ISSUE TITLE
Apply CI to Tutorial

### ISSUE THREAD

**Issue by pdg744** [risc0/risc0#811]
The instructions in the tutorial often ends up out of sync with reality. 
I wonder whether we can get CI to check the correctness of the tutorial... 

Edit: I'll add that there's a related but separate question of whether we can check correctness of code snippets on the website.

**Comment by pdg744** [comment]
I think @SchmErik had some thoughts on this

**Comment by samtvlabs** [comment]
Hey wanted to take this on , and wondered how it was different from [here ](https://github.com/risc0/risc0/blob/main/.github/workflows/main.yml#L106-L144)

**Comment by SchmErik** [comment]
It's different because the code lies in the README.md file here https://github.com/risc0/risc0/blob/main/examples/factors/README.md

I wonder if it would make sense to write a script to generate the README.md. The issue we have is that this gets out of sync with whatever changes we make to the factors example so we need a way to 1) update the code easily when the example changes and 2) catch when we forget to update the code in CI.

For 1) I think we could write a small program to generate the README.md where the bootstrap program copy/pastes lines from the tutorial rust files and paste to the README.md file. When we modify the examples, the bootstrap command should be run to regenerate the README.md file and we should commit the file.

For 2) As a part of the CI process, we could run bootstrap, to re-generate the README.md if there are any differences between the committed README.md and the generated README.md, fail the CI.

**Comment by samtvlabs** [comment]
Happy to take this on

**Comment by SchmErik** [comment]
Here's another idea - we could have the tutorial written in some form of Markdown except when we need to reference  code, we can use some sort of custom markdown text to indicate "copy/paste lines x-y from file z".
During the bootstrapping process, the rust program can look into the Markdown file with this extra extension and generate the README containing the actual code
