### ISSUE TITLE
Update terminology following the new sequence diagram

### ISSUE THREAD

**Issue by tzerrell** [risc0/risc0#916]
The sequence diagram update PR (https://github.com/risc0/website/pull/296) updates some of the terminology used in our proof system. Make the corresponding changes to the proof system code (i.e. in comments, variable names, docs, ...)

**Comment by pdg744** [comment]
#296 introduces the term "auxiliary" for what has been called the "accum" section. Unfortunately, this change isn't so straight-forward, because the term "accum" appears in many places to mean many things in the codebase. 

I'm going to open a few issues to describe some of the codebase terminology issues I'd like to address.

**Comment by pdg744** [comment]
The following issues are more actionable descriptions of what needs to be done here; closing this in favor of those:

#921 
#922 
#925
