### ISSUE TITLE
risc0-build: implement memory layout to prevent the stack and heap from running into eachother

### ISSUE THREAD

**Issue by SchmErik** [risc0/risc0#918]
Current memory layout of guest programs results in higher cost due to the memory layout spanning both ends of available guest memory. An alternative layout can start in the middle and have memory grow to the high/low end. This can help with small programs that do not consume a lot of memory. This can be a feature that users opt in to. It would be even better if we could allow the stack size to be configurable within a guest's cargo.toml.

**Comment by jbruestle** [comment]
I think we should make a 'start in the middle' memory layout the default because the stack growing into the heap is actually a potential security issue, and as long as we pick a 'smallish' stack size (like 2 MB or thereabouts), it doesn't waste too much memory and also 2MB is a lot of stack for normal use cases.
